### ISSUE TITLE
./reverie.sh not starting after install

### ISSUE THREAD

**Issue by filebe777** [baguswiratmaadi/reverie#1]
Error Message - 
Your choice [1-3]   :1 
usr/bin/reverie.sh: line 25: no such file or directory  

same error for https - 2

**Comment by ghost** [comment]
you can run reverie.sh without installing it

just type ./reverie.sh on terminal in your reverie directory

or you can install manually like this

cp http.sh /usr/bin/
chmod 777 /usr/bin/http.sh
cp https.sh /usr/bin/
chmod 777 /usr/bin/https.sh
cp reverie.sh /usr/bin/
chmod 777 /usr/bin/reverie.sh
